spring:
  application:
    name: Project Visual Studio Code
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/users
    
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
 port: 8084    


management:
  tracing:
    sampling:
      probability: 1.0


