server:
  port: ${PORT:8081} #8081

spring:
  application:
    name: msvc-usuarios
  datasource:
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    url: jdbc:postgresql://${DB_HOST:postgresql-container}:5432/${DB_NAME:db_course}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  #configurcion spring cloud
  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true
  profiles:
    active: dev

#name services
#service:
#  usuarios: ${SERVICE_USUARIOS:service-usuarios:8081}
