spring:
  application:
    name: services-email
  datasource:
    url: jdbc:postgresql://localhost:5432/database_

# eureka instance
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


#configuration aws
aws:
  secret:
    key: ${SECRET_KEY}
  access:
    key: ${ACCESS_KEY}
  region: ${AWS_REGION}
  bucket:
    name: bucket-files-usuarios
    url: https://bucket-files-usuarios.s3.us-east-1.amazonaws.com/
