kind: ConfigMap
apiVersion: v1
metadata:
  name: msvc-gateway
data:
  application.yml: |-
    spring:
      cloud:
        gateway:
          discovery:
            locator:
              enabled: true
          routes:
            - id: msvc-usuarios
              uri: lb://msvc-usuarios
              predicates:
                - Path=/api/usuarios/**
            - id: msvc-cursos
              uri: lb://msvc-cursos
              predicates:
                - Path=/api/cursos/**
