apiVersion: v1
kind: ConfigMap
metadata:
    name: msvc-curso
data:
    port: "8082"   # Se ha envuelto el valor numérico en comillas para que sea una cadena
    db_host: postgresql_container
    postgres_user: root
    #ahora se configura por secret.yaml.
    #postgres_password: root
    db_name: db_course
    service_usuarios: msvc-usuarios:8081

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8081"
  db_host: postgresql_container
  postgres_user: root
  postgres_password: root
  db_name: db_course
  msvc-usuarios.yaml: |-
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando ambiente de desarrollo
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Configurando ambiente de produccion
