apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-cursos
  template:
    metadata:
      labels:
        app: msvc-cursos
    spec:
      containers:
        - image: manuonda/curso-docker-msc-curso:latest
          name: curso-docker-msc-curso
          ports:
            - containerPort: 8082
          env :
            - name: MY_NODE_NAME
              valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
               fieldRef:
                fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
               fieldRef:
                fieldPath: spec.serviceAccountName
            - name: SERVICE_USUARIOS
              #value: msvc-usuarios:8081
              valueFrom:
                configMapKeyRef:
                  name: msvc-curso
                  key: service_usuarios
          resources: {}
