apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: msvc-usuarios
  name: msvc-usuarios
spec:
  replicas: 4
  selector:
    matchLabels:
      app: msvc-usuarios
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: msvc-usuarios
    spec:
      containers:
        - image: manuonda/curso-docker-msc-usuarios:latest
          name: curso-docker-msc-usuarios
          #referencia a actuator
          ports:
            - containerPort: 8081
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          #configuration of actuator
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5 #levanta despues mi container de 5 segundos
            periodSeconds: 20  #se ejecuta un perido de 10 segundos de veirification
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 10
          #definition of resources
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"

status: {}
