apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-container
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgresql-container
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        ports:
        - containerPort: 5432
        env :
        - name: POSTGRES_USER
          #value: root
          valueFrom:
            configMapKeyRef:
              name: msvc-curso
              key: postgres_user
        - name: POSTGRES_PASSWORD
          #value: root
          valueFrom:
            secretKeyRef:
              name: secret-postgres
              key: postgres_password
        - name: DB_HOST
          #value: postgresql-container
          valueFrom:
            configMapKeyRef:
              name: msvc-curso
              key: db_host
        - name: POSTGRES_DB
          #value: db_course
          valueFrom:
            configMapKeyRef:
              name: msvc-curso
              key: db_name
        volumeMounts:
         - name: postgres-data
           mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgresql-data-pvc
            readOnly: false
          #hostPath:    #hostPath es fuera del pod
          # path: /var/lib/postgresql/data
          # type: DirectoryOrCreate
status: {}
