
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgresql_container
    ports:
      - "5432:5432"
    environment:
     - 'POSTGRES_USER=root'
     - 'POSTGRES_PASSWORD=root'
     - 'POSTGRES_DB=db_course'
    volumes:
      - ./data_postgresql:/var/lib/postgresql/data
    networks:
      - spring


  msc-usuarios:
    container_name: service-usuarios
    build:
      context: .
      dockerfile: microservice-usuarios/Dockerfile
    ports:
      - "8081:8081"
    environment:
     - ./microservice-usuarios/.env
    depends_on:
      - postgres
    networks:
      - spring
    restart: always


  msc-cursos:
    container_name: service-cursos
    build:
      context: .
      dockerfile: microservicio-curso/Dockerfile
    ports:
      - "8082:8082"
    environment:
     - ./microservicio-curso/.env
    depends_on:
      - postgres
      - msc-usuarios
    networks:
      - spring
    restart: always

volumes:
  postgres_data:

networks:
  spring:
    name: spring