apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  # minikube storageClassName: standard
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path:  /var/lib/postgresql/data   # Reemplaza esto con la ruta real en tu host
    type: DirectoryOrCreate