apiVersion: v1
kind: Service
metadata:
  name: msvc-cursos
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: msvc-cursos
  sessionAffinity: None
  type: LoadBalancer

