apiVersion: v1
kind: Service
metadata:
  name: postgresql-container
spec:
  type: ClusterIP  # Cambiado a ClusterIP
  selector:
    app: postgresql-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432