apiVersion: v1
kind: Service
metadata:
  name: msvc-usuarios
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: msvc-usuarios
  sessionAffinity: None
  type: LoadBalancer

