spring:
  application:
    name: test-container
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  
