spring:
  application:
    name: patter-design-jpa
  datasource :
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: "jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE"
    h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    