server:
  port: ${PORT:8082} #8082

spring:
  application:
    name: msvc-cursos
  datasource:
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    url: jdbc:postgresql://${DB_HOST:postgresql-container}:5432/${DB_NAME:db_course}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true
  profiles:
    active: dev

#name services : msvc-usuarios seria el nombre del microservicio levantado en el docker
service:
  usuarios: ${SERVICE_USUARIOS:msvc-usuarios:8081}