server:
  port: ${PORT:8082} #8082

spring:
  application:
    name: service-cursos
  datasource:
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    url: jdbc:postgresql://${DB_HOST:postgresql_container}:5432/${DB_NAME:db_course}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

#name services
service:
  usuarios: ${SERVICE_USUARIOS:service-usuarios:8081}