server:
  port: 9090


spring:
  application:
    name: service-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: productos
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/productos/**
        - id: categorias
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/categorias/**
        - id: inventario
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/inventarios/**
        - id: email
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/emails/**
        - id: usuarios
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/usuarios/**






