version : '1'
services: 
  postgresql:
    container_name: container-psg
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    ports:
      - 5433:5432
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2.24
    ports:
      - 9411:9411

    
