server:
  port: 8080
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hiberante.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true