spring:
  application:
    name: service-producto
  datasource:
    url: jdbc:postgresql://localhost:5432/db_commerce
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    baseline-on-migrate: true

  #configuration redis
  redis:
    host: localhost
    port: 6379

  #kafka producer config
  kafka:
    bootstrap-servers: localhost:29092
    topic:
      reposicion_producto: reposicion_producto
      venta_producto: venta_producto
      agregar_producto: agregar_producto
      envio_email: envio_email

#server port spring boot
server:
  port: 8083

#swagger configuration
spring-doc:
  api-docs:
    path: /api-docs

# actuator
management:
  endpoint:
    health:
      show-details: always # Para mostrar detalles en el endpoint de health
  endpoints:
    web:
      exposure:
        include: '*' # Para exponer todos los endpoints de Actuator, puedes personalizar esta lista según tus necesidades


#configuration eureka client
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka