spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database : postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

spring.eruka.server.

