eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  #para que no registre por si mismo
    fetch-registry: false   #no necesitamos buscar el registro
    service-url:
      deafultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    
server:
  port: 8761
  
spring:
  application:
    name: discovery