services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=database_producto'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
