spring:
  application:
    name: application-crud
  datasource:
      url: jdbc://postgresql://localhost:5432/mydatabase
      username: myuser
      password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#enable actuator metrics
management:
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always



secret:
  key: 123o1321290123j12ljh12iou